version: "3.8"

services:
  daemon:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - LOGGER_LEVEL=debug
      - S3_ENDPOINT=minio:9000
      - S3_BUCKET=backup
      - S3_ACCESS_ID=minioadmin
      - S3_ACCESS_SECRET=minioadmin
    networks:
      - intranet
    depends_on:
      - createbuckets
      - minio
      - postgres
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    expose:
      - 9000:9000
      - 9001:9001
    networks:
      - intranet
    volumes:
      - ~/minio/data:/data
  createbuckets:
    image: quay.io/minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/backup;
      exit 0;
      "
    networks:
      - intranet
    depends_on:
      - minio
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - intranet
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data

networks:
  intranet:
