version: "3.8"

services:
  daemon:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - LOGGER_LEVEL=debug
      - S3_ENDPOINT=minio:9000
      - S3_BUCKET=backup
      - S3_ID=minioadmin
      - S3_SECRET=minioadmin
    networks:
      - intranet
    depends_on:
      - createbuckets
      - minio
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    expose:
      - 9000:9000
      - 9001:9001
    networks:
      - intranet
  createbuckets:
    image: quay.io/minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/backup;
      exit 0;
      "
    networks:
      - intranet
    depends_on:
      - minio

networks:
  intranet:
